format = """$shell$character"""

add_newline = false

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[shell]
fish_indicator = '󰈺 '
powershell_indicator = '_'
bash_indicator = ''
unknown_indicator = 'mystery shell'
style = 'green bold'
disabled = false
